package_update: true
package_upgrade: true
packages: ['docker-ce']

apt:
  preserve_sources_list: true
  sources:
    docker.list:
      source: "deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable"
      keyid: 0EBFCD88

runcmd:
  - ["systemctl", "start", "docker"]